### ISSUE TITLE
Variable Overrides

### ISSUE THREAD

**Issue by nyarthan** [titanom/bwenv#21]
Requires toml v1.1

```toml
[profiles.development]
overrides = {
  FORCE_COLOR = 1
}
```
